import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./context/client-provider";
import Navbar from "./Components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
import PathChecker from "./PathChecker";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <PathChecker>{children}</PathChecker>
        </Provider>
      </body>
    </html>
  );
}
